### ISSUE TITLE
[Question] How to use with a VIPER architecture?

### ISSUE THREAD

**Issue by elprl** [hmlongco/Factory#14]
I love the simplicity of this DI package, but I'm finding the documentation a little confusing. My adoption of the package would depend on how it deals with a 'Clean Architecture' used in a professional workspace. Right now I'm struggling to understand how to use this package with a VIPER architecture. We use a similar structure to here:
https://github.com/theswiftdev/tutorials/blob/master/VIPER/VIPERAndSwiftUI/VIPERAndSwiftUI/Sources/VIPER.swift

I began with this (below) but it doesn't compile (not even sure this is the correct approach):
```swift
import Foundation
import SwiftUI
import Factory

// MARK: - Router
typealias ListViewRouterInterface = any RouterInterface & ListViewRouterPresenterInterface

protocol ListViewRouterPresenterInterface: RouterPresenterInterface {
    func showDetails(for animal: Animal) -> any View
}

// MARK: - Presenter

typealias ListViewPresenterInterface = any PresenterInterface & ListViewPresenterRouterInterface & ListViewPresenterInteractorInterface & ListViewPresenterViewInterface

protocol ListViewPresenterRouterInterface: PresenterRouterInterface {

}

protocol ListViewPresenterInteractorInterface: PresenterInteractorInterface {
    func didLoad(animals: [Animal])
}

protocol ListViewPresenterViewInterface: PresenterViewInterface {
    var viewModel: ListViewModel? { get set }
    func onAppear()
    func onBtnPress(animal: String)
}

// MARK: - Interactor
typealias ListViewInteractorInterface = any InteractorInterface & ListViewInteractorPresenterInterface

protocol ListViewInteractorPresenterInterface: InteractorPresenterInterface {
    func fetchItems()
}

extension Container {
    static let apiService = Factory<APIServiceProtocol>(scope: .shared) { APIService() }
}

class ListViewContainer: SharedContainer {
    static let viewModel = Factory<ListViewModel>(scope: .shared) { ListViewModel() }
    static let presenter = Factory<ListViewPresenterInterface>(scope: .shared) { ListViewPresenter() }
    static let interactor = Factory<ListViewInteractorInterface>(scope: .shared) { ListViewInteractor() }
    static let router = Factory<ListViewRouterInterface>(scope: .shared) { ListViewRouter() }
}

final class ListViewModule {
    @Injected(ListViewContainer.viewModel) private var viewModel
    @Injected(ListViewContainer.presenter) private var presenter
    @Injected(ListViewContainer.interactor) private var interactor
    @Injected(ListViewContainer.router) private var router

    func build() -> some View {
        presenter.viewModel = self.viewModel
        let view = ListView(presenter: presenter)
        presenter.interactor = self.interactor
        presenter.router = self.router
        interactor.presenter = self.presenter
        router.presenter = self.presenter
        return view
    }
```

Do you have any advice on how to do this in a VIPER architecture? I think this would be a great example to add to your samples folder. The fact that VIPER has various Input and Output contracts make it difficult.

**Comment by hmlongco** [comment]
Not sure where to start here. You're right that the code doesn't compile. Give me me a working version that compiles w/o DI and I might be able to help.

Part of the problem is that you're trying to make everything a protocol, and I think you're getting into trouble with Swift's famous associated type requirements on the presenter that needs to return "some" view.

Not everything needs or wants to be a protocol. See: [Using View Model Protocols in SwiftUI? You’re Doing it Wrong.](https://betterprogramming.pub/swiftui-view-models-are-not-protocols-8c415c0325b1) for a discussion of how to swap out backend services.

That said, I'm going to go on the record as saying that VIPER is a fairly decent methodology... for UIKit. 

The entire system is designed to wire together components in an old-school, imperative, direct reference delegate mechanism. And does that in order to provide control and update and segregation mechanisms that in more modern architectures would be done with RxSwift or Combine, or in the case of SwiftUI, with state observation and lightweight view composition.

Further, VIPER is a somewhat verbose and complex architectural system designed to slim down and manage heavyweight UIViewControllers and the choices it makes are, IMHO, is extremely ill-suited to SwiftUI. I've written about it somewhat extensively in [SwiftUI: Choosing an Application Architecture](https://betterprogramming.pub/swiftui-choosing-an-application-architecture-6ec9289f8e8f).

**Comment by elprl** [comment]
I've just seen those 1.2.5 changes - nice one. That makes it Interesting, as I've been wondering whether to put the Injections in the individual classes, versus in the module builder. In fact, I'll just try it in a new branch.

**Comment by elprl** [comment]
I tried on a new branch here:
https://github.com/elprl/Factory/tree/viper-spike-weak-inject

It doesn't compile because ```WeakLazyInjected``` requires a class type rather than my protocols. 
```swift 
final class ListViewInteractor: ListViewInteractorInterface {
    @WeakLazyInjected(ListViewContainer.presenterInteractor) var presenter // Error: Generic struct 'WeakLazyInjected' requires that 'any ListViewPresenterInteractorInterface' be a class type
    @Injected(Container.apiService) private var apiService
}
```

So looks like it can't be done in the way I'd hoped.

**Comment by hmlongco** [comment]
Any luck?

Also, I put together a few thoughts on SwiftUI and VIPER here....
https://michaellong.medium.com/viper-for-swiftui-please-no-ee61ce99694c

**Comment by hmlongco** [comment]
I think you can also conform your protocols to AnyObject.

**Comment by elprl** [comment]
They already conform to AnyObject. It needs to be a class as the error states.

**Comment by hmlongco** [comment]
I may need to file a radar on that as Swift should be able to figure out the conformance.

This, for example, works:
```swift
weak var presenter: ListViewPresenterInteractorInterface? = ListViewContainer.presenterInteractor()
```
Without the AnyObject conformance on the protocol the assignment fails complaining about assigning a non-class-based protocol to weak variable.

**Comment by hmlongco** [comment]
There are some updates in 1.2.7.

**Comment by hmlongco** [comment]
Because the wrapped value returned by WeakLazyInjected is optional? It is weak, after all.

You can start explicitly unwrapping things, but as I wrote in the section on optionals, doing so violates the core premise on which Factory was built in the first place: Your code is guaranteed to be safe.

```swift
protocol ListViewRouterInterface {
    /*weak*/ var presenter: ListViewPresenterRouterInterface! { get set }
}

final class ListViewRouter: ListViewRouterInterface {
    @WeakLazyInjected(ListViewContainer.presenterRouter) var presenter: ListViewPresenterRouterInterface!
}
```

**Comment by elprl** [comment]
Seems to be working well. I added some sample unit tests and all seemed to work well.
