### ISSUE TITLE
very heavy load on the CPU

### ISSUE THREAD

**Issue by Meffistofel1992** [hmlongco/Factory#157]
The project is not big
Mainly uses @Injected(\.)
@InjectedObject(\.)

when  I'm just writing code or switching between xcode files, it lags a lot
what can you suggest? I like the library, but it is difficult to work because of lags

xCode 15.0 Releas
Mac m1 pro 2021

The more I use @injected or @InjectedObject the more often the CPU hangs and spikes

**Comment by EvanCooper9** [comment]
Came here to report the same issue. Simply including the line `import Factory` causes text editing to lag when typing, adding/deleting new lines, etc (even on small files).

Same specs:
Xcode 15.0 (15A240d)
MBP M1 Pro 2021

Anecdotally, this wasn't an issue with Xcode 14.x. I only started experiencing this when I upgraded to Sonoma & Xcode 15. Unfortunately I can't go back to Xcode 14.

**Comment by hmlongco** [comment]
How is Factory imported into the project? SPM?

**Comment by EvanCooper9** [comment]
For me, yes

**Comment by edkhrian** [comment]
I experienced the same problem so I couldn't even edit files because of the lags. So I opened the project with another editor and added types to all injected factories. 
For example, instead of
````swift
struct MyView: View {
  @Injected(\.apiRepository) private var apiRepository
  // ...
}
````
I added type to the injected factory
````swift
struct MyView: View {
  @Injected(\.apiRepository) private var apiRepository: APIRepository
  // ...
}
````
And it solved the problem. I guess xcode lags trying to resolve all implicitly injected types

**Comment by hmlongco** [comment]
Can't reproduce this, but it looks as if specifying the type can alleviate the issue. Did make one change to InjectedObject to explicitly specify type of internal StateObject.

**Comment by VladOrackle** [comment]
Same issue on Xcode 15.0.1, specifying types helps, but it's strange that it even happens

**Comment by nashfive** [comment]
I noticed exactly the same problem. Sometimes it's even worse, I have to force-quit Xcode (forever beach-balling...). Sometimes I even have to edit the source with an external text editor ! 
Xcode 15.1b2 seems to fix the worst case scenario but some source files still exhibits hangs when scrolling, so adding explicit types fixes it.

**Comment by KiritoBeater** [comment]
I experienced the same problem, and my solution is to replace `@Injected(\. keypath)` with `resolve(\.keypath)`.

For example, instead of
```swift
struct MyView: View {
  @Injected(\.apiRepository) var apiRepository
  // ...
}
```

Using the the global functions which Factory provide. https://hmlongco.github.io/Factory/documentation/factory/resolutions/#Global-Keypath-Resolution-from-Shared-Container
```swift
struct MyView: View {
  var apiRepository = resolve(\.apiRepository) 
  // ...
}
```

it solved the problem.
