### ISSUE TITLE
is it possible to inject swiftui view through factory?

### ISSUE THREAD

**Issue by abdahad1996** [hmlongco/Factory#176]
so is something like this possible?
<img width="740" alt="Screenshot 2024-01-07 at 01 33 45" src="https://github.com/hmlongco/Factory/assets/28492677/abe1c4ae-de1c-4787-8557-454d1c9d7f04">

**Comment by hmlongco** [comment]
Don't know why you'd want to, as injection should really be confined to view models and services. Attempting to do so usually ends up where you are due to the associated type problem.

If, for some reason you feel you must inject a view you're probably going to need to use AnyView to type erase the associated body type.
