### ISSUE TITLE
Parallel Testing Fails (Occasionally)

### ISSUE THREAD

**Issue by a-shatou** [hmlongco/Factory#231]
In setting up a test, I inject the dependency like this:

`Container.shared.mailComposer.register { MailComposerMock() }`

Now, if the tests are running in parallel in the same test case, there is a chance that the injected mock is different than the one intended. Here is an example.

Assume all tests are running serially.

Test 1: setup -> creates a new mock.
Test 1: test function -> uses the same mock. Test succeeds.

Test 2: setup -> creates a second new mock.
Test 2: test function -> uses this second new mock. Test succeeds.

Now, let's see what _can_ happen if tests are run in parallel

Test 1: setup -> creates a new mock.
Test 2: setup -> creates a second new mock.
Test 1: test function -> uses the second mock not the first one. Test fails.

Unfortunately, the tests do _not_ have to fail. It could run several times successfully only to fail after a couple of successful runs.
Also, note that this scenario happens even if the dependency is not `shared` or `singleton`. Is there a way to avoid this without disabling parallel testing?

**Comment by hmlongco** [comment]
If you inject a specific container instance into your view models or services, then you can build and inject a separate container for each set of tests so that parallel testing works. 

If you access Container.shared or use one of the @Injected property wrappers that depend on Container.shared, then your tests need to be serialized.

This issue isn't specific to Factor or Resolver, and in fact impacts other scenarios like using a URLProtocol on URLSession.shared, or testing any code that depends on a global or statically shared variable.

https://www.swiftwithvincent.com/blog/how-to-mock-any-network-call-with-urlprotocol

**Comment by a-shatou** [comment]
Well, that makes a lot of sense. I will look into using custom container instances later. For now, I am serializing all tests. Will take some time to run (currently around 4 minutes) but the custom container solution should resolve that later. Thanks for the quick reply.
