### ISSUE TITLE
Workspace and clean architecture setup

### ISSUE THREAD

**Issue by HaakonL** [hmlongco/Factory#39]
Hi, I am not able to wrap my head around how to best use Factory in a multi-project setup, formed around a clean architecture pattern. This was easy with Resolver, but in Factory it seems to lead to circular references - unless you accept a "doubling" of references.

Consider the following architecture in an XCWorkspace:

App (contains the SwiftUI project with views and viewmodels)
Core (framework that contains the protocols and models)
Services (framework that contains the services, for example external api integrations)
Bootstrap (framework that bootstraps Services and Core for dependency injection/ioc)

In Factory, registrations made in Bootstrap will not be visible to App or Services.

In a clean architecture using xcworkspace, separation is the key benefit. App should not know about the concrete implementations of the services, it will only operate on the protocols. Therefore, App does not have a reference to Services, only to Core where the protocols live. And because of that, a separate project needs to do the bootstrapping, ie Bootstrap.

My Bootstrap project contains only this, and embeds the Core and Services projects to make this work:

extension SharedContainer {
    static let httpClient = Factory(scope: .singleton) { HttpClient() as HttpClientProtocol }
    static let linksService = Factory(scope: .singleton) { LinksService() as LinksServiceProtocol }
}

My App project embeds the Bootstrap project and the Core project

My Services project embeds Core.

Services needs an instance of HttpClientProtocol: @Injected(Container.httpClient) private var httpClient: HttpClientProtocol

But that will not work, since the registration is done in Bootstrap. Services has no notion of Bootstrap at all.

Is there a way with Factory? If not, the Inversion of Control part of Dependency Injection is missing in this framework, and it will only work for monolith projects.

**Comment by HaakonL** [comment]
https://github.com/HaakonL/Speedfriends

In there, I have a multi project setup with xcworkspace, clean architecture and resolver. Tried porting it to Factory without luck.

**Comment by hmlongco** [comment]
See if this helps...
https://betterprogramming.pub/factory-multiple-module-registration-f9d19721a31d?sk=a03d78484d8c351762306ff00a8be67c

**Comment by HaakonL** [comment]
Thanks, that solved the issue for me :)

**Comment by HaakonL** [comment]
I wonder if it is now un-solved again, with the update to Factory 2?

App is the main project, and it holds a reference to the Bootstrap framework. It also references Core to know about the Protocols. But it does not reference Services or Persistence.

Bootstrap references Core where the Protocols are, and Services/Persistence where the concrete implementations are. Bootstrap ties the protocols and implementations together.

Services and Persistence references Core to know about the protocols.

<img width="1503" alt="Skjermbilde 2023-03-08 kl  13 56 41" src="https://user-images.githubusercontent.com/508432/223719172-6efdd4a9-a234-4819-ad52-4a00366378a4.png">

**Comment by HaakonL** [comment]
Example project: [https://github.com/HaakonL/Speedfriends/tree/factory2](https://github.com/HaakonL/Speedfriends/tree/factory2)

**Comment by hmlongco** [comment]
2.0 changed things up, true, but anything that worked and was visible in 1.0 should be equally visible in 2.0, provided it's publicly marked as such.

See: https://hmlongco.github.io/Factory/documentation/factory/modules

**Comment by HaakonL** [comment]
Hmm, no, this wont work (for me), it will break the principle that the Core module, referred to as ModuleP in your documentation, should have no internal or external dependencies.

**Comment by hmlongco** [comment]
So having Core import Factory would break a self-imposed rule? From my perspective, the DI system lives outside of the normal chain of command.

Only other option then, as far as I can see, is then to create a Dependencies module that can do the same thing. It can see core, and other modules need to import Core and Dependencies to get models AND access to APIs.

**Comment by HaakonL** [comment]
I will give this a shot in the linked example project, but I fear that it will lead to circular dependencies. The requirement is not self-imposed, though, but needed to completely separate the frontend from the backend, and a crucial part of the clean architecture philosophy.

**Comment by ninokierulf** [comment]
> See if this helps...
> https://betterprogramming.pub/factory-multiple-module-registration-f9d19721a31d?sk=a03d78484d8c351762306ff00a8be67c

After reading the article, can I assume that multiple modules requiring a `Factory<T>` will need to depend on a lower module that defines the optional pattern `var service:  Factory<ServiceContract?> { self { nil } }`? Because with Inversion of Control, there should be no concrete implementation at the level of requesting of desired service. Any injected object will then always have the `guard` check.

Example Module Structure:

App - where concrete services should be registered
^^^
Feature Modules - objects requiring a non-concrete service  to be  injected
^^^^^^^^^^^^^
Core - ??? place where service Factory are defined (but nil at this point)

**Comment by drekka** [comment]
Just read the article and realised I've done exactly that setup in the project I'm working on. 

In mine, I have a "domain" module which contains all the models and service protocols, a "UI" module which has all the UI views and view models, and a "services" module which implements "domain"'s service protocols. The only place which has access to both the views from "UI" and the service implementations from "services" is the app itself. So if a view model in "UI" needs a service, it can only see the protocol, not the implementation and visa versa, the services cannot see the views.

Factory 2 made this easy to deal with. However instead of registering `nil` optionals in "domain", I've registered `fatalError(...)` because I don't want optional services and also because I want the app to fall had and fast if I've stuffed up. 

The only thing I haven't done is use the auto-registering stuff because I hadn't seen it. So I'll be updating my code as it's clearly superior to manually managing things and will remove a couple of `@LazyInjected(...)` properties I had in my main app class.

**Comment by hmlongco** [comment]
@drekka I'll see if I can clear some of that up in the documentation.

That said, I've been promoting the optional approach primarily because doing `fatalError` and going boom is kind of what Factory was trying to avoid in the first place. ;)

**Comment by drekka** [comment]
> That said, I've been promoting the optional approach primarily because doing `fatalError` and going boom is kind of what Factory was trying to avoid in the first place. ;)

Yeah it's one of those programming problems I think comes down to context. ie. does your code swallow an error (or developer mistake) and keep going if it can, or does it assert more aggressively, displaying an error or shutting down. I tend to lean towards the more aggressive approach only because I've spent a lot of time in the past debugging strange issues because some developer decided to just quietly swallow some error in the code, or because they intended to handle it and just never got back to that section of code.

**Comment by hmlongco** [comment]
@drekka  What if you could do something like...
```swift
extension Container {
    var serviceThatNeedsRegistration: Factory<MyService?> { promised() }
}
```
Based on something like...
```swift
extension ManagedContainer {
    public func promised<T>(key: String = #function) -> Factory<T?>  {
        Factory<T?>(self, key: key) {
            #if DEBUG
            fatalError("\(T.self) was not registerd")
            #else
            nil
            #endif
        }
    }
}
```
So app crashes and fails fast in debug mode, but doesn't when released?

**Comment by hmlongco** [comment]
Actually I've been playing with that and like it more and more.
```swift
extension Container {
    var requiredService: Factory<MyService?> { promised() }
}
```
Will probably make it into 2.1...

**Comment by drekka** [comment]
Yeah, it's look really nice. Particularly the `promised()` which is clearly saying "Hey - this will be filled in later."

**Comment by drekka** [comment]
The only issue I can think of is that you may need to have some sort of switch so that you can run with nils in debug during testing (unit and UI) because you will still need a way to test out `nil` responses. Technically never occur because the fatals will make developers fill in the blanks, but because the factory is still returning an optional, the rest of the code has to handle it and therefore "technically" what happens when a `nil` is return should tested.

**Comment by hmlongco** [comment]
Thought of that.
```swift
FactoryContext.promiseTriggersError = false
```

**Comment by hmlongco** [comment]
Keep in mind WIP, but....

**Comment by hmlongco** [comment]
@drekka Promised is in the 2.1 develop branch. Also note that if you pull the 2.1 branch I updated the DocC documentation for multiple modules fairly heavily.

If you could glance at it and see if it clears up some of the confusion I'd appreciate it.

**Comment by drekka** [comment]
Will do.

**Comment by drekka** [comment]
Just tried to do an archive of my project which is using the `develop` branch code. Failed to compile because the new `resetAndTriggerFatalError(...)` code is wrapped in `#if DEBUG ...#endif` which excludes it from an archive built (which I'm doing for TestFlight).

**Comment by hmlongco** [comment]
@drekka Did you leave a note regarding archiving issues? Just archived test project w/o problems.

**Comment by drekka** [comment]
Yeah, sorry. Was my bad. Didn't clear the project space before building.

**Comment by ninokierulf** [comment]
> > See if this helps...
> > https://betterprogramming.pub/factory-multiple-module-registration-f9d19721a31d?sk=a03d78484d8c351762306ff00a8be67c
> 
> After reading the article, can I assume that multiple modules requiring a `Factory<T>` will need to depend on a lower module that defines the optional pattern `var service: Factory<ServiceContract?> { self { nil } }`? Because with Inversion of Control, there should be no concrete implementation at the level of requesting of desired service. Any injected object will then always have the `guard` check.
> 
> Example Module Structure:
> 
> App - where concrete services should be registered ^^^ Feature Modules - objects requiring a non-concrete service to be injected ^^^^^^^^^^^^^ Core - ??? place where service Factory are defined (but nil at this point)

I realized I could use the Null Object pattern to avoid littering codebase with optional.

```swift
public protocol EmailAuthServiceProtocol {
    func authenticate(email: EmailAddress, password: EmailPassword) async throws -> User
}

public struct NullEmailAuthService: EmailAuthServiceProtocol {
    public init() {}

    public func authenticate(email: EmailAddress, password: EmailPassword) async throws -> User {
        throw EmailAuthError.nullObject
    }
}

public enum EmailAuthError: Error {
    case nullObject
}

```

lower level module can define 
```swift
extension Container {
    var emailPasswordAuth: Factory<EmailAuthServiceProtocol> {
        self { NullEmailAuthService() }
    }
}
```

and Root composition level can override by
```swift
Container.shared.emailPasswordAuth.register { RealEmailAuthService() }
```

**Comment by hmlongco** [comment]
@ninokierulf Bonus points for NullObject. That's a DI staple and definitely a solution that probably should be mentioned in the docs.
